spring:
  application:
    name: gifbottary
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  #개발용 임시 키
  jwt:
    secret-key: gifbottary-local-development-secret-key-123456789
    access-token-expiration: 3600000